/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import model.Empleado;

/**
 *
 * @author PAUL
 */
public class EdicionEmpleado extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EdicionEmpleado.class.getName());

    private ArrayList<Empleado> listaMeseros;
    private ArrayList<Empleado> listaCocineros;
    private ArrayList<Empleado> listaCajeros;
    private ArrayList<Empleado> listaT ;
    private String nombreTemporal;
    private PantallaPrincipal principal;
    
    
    /**
     * Creates new form editarEmpleado
     * @param principal
     * @param listaMeseros
     * @param listaCocineros
     * @param listaCajeros
     */
    public EdicionEmpleado(PantallaPrincipal principal, ArrayList<Empleado> listaMeseros, ArrayList<Empleado> listaCocineros, ArrayList<Empleado> listaCajeros) {
        initComponents();
        this.principal = principal;
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.listaMeseros = listaMeseros;
        this.listaCocineros = listaCocineros;
        this.listaCajeros = listaCajeros;
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                principal.llenadoTablasGeneral();
            }
        });
    }

    public void agregarCb(JComboBox<String> elComboBox, String nombre) {
        
        boolean existe = false;
        for (int i = 0; i < elComboBox.getItemCount(); i++) {
            if (elComboBox.getItemAt(i).equalsIgnoreCase(nombre)) { 
                existe = true;
                break;
            }
        }
        if (!existe) {
            elComboBox.addItem(nombre);
        }
    }
    public void llenadoTF(ArrayList<Empleado> listaT){
        String selec = elComboBox.getSelectedItem().toString();
        nombreTemporal = selec;
        var a = listaT.stream().filter(p->p.getNombre().equalsIgnoreCase(selec)).findFirst().orElse(null);
        if (a != null){
            tfNombre.setText(a.getNombre());
            tfApellido.setText(a.getApellido());
            tfDNI.setText(a.getDNI());
            tfTelefono.setText(a.getTelefono());
            tfEmail.setText(a.getEmail());
            cbElegirTipo.setSelectedItem(a.getTipo());
            tfSueldo.setText(String.valueOf(a.getSueldo()));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        elComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfApellido = new javax.swing.JTextField();
        tfDNI = new javax.swing.JTextField();
        tfTelefono = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rbMeseros = new javax.swing.JRadioButton();
        rbCocineros = new javax.swing.JRadioButton();
        rbCajeros = new javax.swing.JRadioButton();
        lbtipo = new javax.swing.JLabel();
        cbElegirTipo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        tfSueldo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editar");

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        elComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        jLabel3.setText("DNI");

        jLabel4.setText("Telefono");

        jLabel5.setText("E-mail");

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel6.setText("Seleccione el cliente que va a editar:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Editar empleado");

        buttonGroup1.add(rbMeseros);
        rbMeseros.setText("Meseros");
        rbMeseros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbMeserosMouseClicked(evt);
            }
        });

        buttonGroup1.add(rbCocineros);
        rbCocineros.setText("Cocineros");
        rbCocineros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbCocinerosMouseClicked(evt);
            }
        });

        buttonGroup1.add(rbCajeros);
        rbCajeros.setText("Cajeros");
        rbCajeros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbCajerosMouseClicked(evt);
            }
        });

        lbtipo.setText("Tipo");

        cbElegirTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Meseros", "Cocineros", "Cajeros" }));

        jLabel8.setText("Sueldo");

        jLabel9.setText("El ID no se puede cambiar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbMeseros)
                                .addGap(30, 30, 30)
                                .addComponent(rbCocineros)
                                .addGap(50, 50, 50)
                                .addComponent(rbCajeros))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)))
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(lbtipo)
                                    .addComponent(jLabel8))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfNombre)
                                    .addComponent(tfApellido)
                                    .addComponent(tfDNI)
                                    .addComponent(tfTelefono)
                                    .addComponent(tfEmail)
                                    .addComponent(cbElegirTipo, 0, 150, Short.MAX_VALUE)
                                    .addComponent(tfSueldo)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(elComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMeseros)
                    .addComponent(rbCajeros)
                    .addComponent(rbCocineros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(elComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbElegirTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtipo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void elComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elComboBoxActionPerformed
        // TODO add your handling code here:
        
        if (rbMeseros.isSelected()){
            for (Empleado e : listaMeseros){
            agregarCb(elComboBox, e.getNombre());
            }
            this.listaT = listaMeseros;
            llenadoTF(listaMeseros);
        }
        if (rbCocineros.isSelected()){
            for (Empleado e : listaCocineros){
                agregarCb(elComboBox, e.getNombre());
            }
            this.listaT = listaCocineros;
            llenadoTF(listaCocineros);
        }
        if (rbCajeros.isSelected()){
            for (Empleado e : listaCajeros){
                agregarCb(elComboBox, e.getNombre());
            }
            this.listaT = listaCajeros;
            llenadoTF(listaT);
        }
    }//GEN-LAST:event_elComboBoxActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        try{
            String nombre = tfNombre.getText();
            String apellido = tfApellido.getText();
            String dni = tfDNI.getText();
            String telefono = tfTelefono.getText();
            String email = tfEmail.getText().trim();
            String patron = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";
            double sueldo = Double.parseDouble(tfSueldo.getText());
            String selec = (String)cbElegirTipo.getSelectedItem();
            if (dni.length() != 8){
                JOptionPane.showMessageDialog(this, "El DNI debe ser de 8 dígitos.");
                return;
            }
            if (!email.matches(patron)) {
                JOptionPane.showMessageDialog(this, "Correo inválido ❌");
                return;
            }
            if(sueldo < 0){
                JOptionPane.showMessageDialog(this, "El sueldo no puede ser menos que 0");
                return;
            }
            var a = listaT.stream().filter(p->p.getNombre().equalsIgnoreCase(nombreTemporal)).findFirst().orElse(null);
            if (a != null){
                a.setNombre(nombre);
                a.setApellido(apellido);
                a.setDNI(dni);
                a.setTelefono(telefono);
                a.setEmail(email);
                a.setSueldo(sueldo);
                JOptionPane.showMessageDialog(this, nombreTemporal+" fue actualizado");
                
                if (rbMeseros.isSelected()){
                    if (selec.equalsIgnoreCase("Cajeros")){
                        listaCajeros.add(a);
                        a.setTipo("Cajero");
                    }
                    if (selec.equalsIgnoreCase("Cocineros")){
                        listaCocineros.add(a);
                        a.setTipo("Cocinero");
                    }
                    listaMeseros.remove(a);
                }
                if (rbCocineros.isSelected()){
                    if (selec.equalsIgnoreCase("Meseros")){
                        listaMeseros.add(a);
                        a.setTipo("Mesero");
                    }
                    if (selec.equalsIgnoreCase("Cajeros")){
                        listaCajeros.add(a);
                        a.setTipo("Cajero");
                    }
                    listaCocineros.remove(a);
                }
                if (rbCajeros.isSelected()){
                    if (selec.equalsIgnoreCase("Meseros")){
                        listaMeseros.add(a);
                        a.setTipo("Mesero");
                    }
                    if (selec.equalsIgnoreCase("Cocineros")){
                        listaCocineros.add(a);
                        a.setTipo("Cocinero");
                    }
                    listaCajeros.remove(a);
                }
                this.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosed(java.awt.event.WindowEvent e) {
                        principal.notificaciones(3);
                    }
                });
                dispose();
            }
            else{
                JOptionPane.showMessageDialog(this, "No existe");
            }
        } catch (HeadlessException | NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Hubieron errores en el registro.");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void rbMeserosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbMeserosMouseClicked
        // TODO add your handling code here:
        elComboBox.removeAllItems();
        if (rbMeseros.isSelected()){
            for (Empleado e : listaMeseros){
            agregarCb(elComboBox, e.getNombre());
            }
            listaT = listaMeseros;
            llenadoTF(listaMeseros);
        }
    }//GEN-LAST:event_rbMeserosMouseClicked

    private void rbCocinerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbCocinerosMouseClicked
        // TODO add your handling code here:
        elComboBox.removeAllItems();
        if (rbCocineros.isSelected()){
            for (Empleado e : listaCocineros){
                agregarCb(elComboBox, e.getNombre());
            }
            listaT = listaCocineros;
            llenadoTF(listaCocineros);
        }
    }//GEN-LAST:event_rbCocinerosMouseClicked

    private void rbCajerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbCajerosMouseClicked
        // TODO add your handling code here:
        elComboBox.removeAllItems();
        if (rbCajeros.isSelected()){
            for (Empleado e : listaCajeros){
                agregarCb(elComboBox, e.getNombre());
            }
            listaT = listaCajeros;
            llenadoTF(listaT);
        }
    }//GEN-LAST:event_rbCajerosMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbElegirTipo;
    private javax.swing.JComboBox<String> elComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbtipo;
    private javax.swing.JRadioButton rbCajeros;
    private javax.swing.JRadioButton rbCocineros;
    private javax.swing.JRadioButton rbMeseros;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfDNI;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfSueldo;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
