
package view;

import java.util.Random;
import controller.Controller;
import controller.ControllerSQL;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Inventario;
import model.Producto;
import model.Venta;
import java.util.Random;
import model.Empleado;
import java.sql.SQLException;

/**
 *
 * @author PAUL
 */
public class RegistroVenta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroVenta.class.getName());
    /**
     * Creates new form resgistrarVenta
     */
    
    
    public Inventario in;
    public DefaultListModel<String> modeloLista = new DefaultListModel<>();
    public ArrayList<String> listaMientras = new ArrayList<>();
    public Venta ventaPrincipal;
    public double total = 0;
    public Controller controlador;
    public PantallaPrincipal principal;
    public LocalDateTime ahora = LocalDateTime.now();
    public String recibo;
    public Random rnd;
    public Empleado mesero;
    public Empleado cajero;
    public Empleado cocinero;
    private Random random = new Random();
    
    public RegistroVenta(Inventario in, Venta ventaPrincipal, Controller contro, PantallaPrincipal principal) {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.in = in;
        this.ventaPrincipal = ventaPrincipal;
        this.controlador = contro;
        this.principal = principal;
        this.rnd = new Random();
        int ran = rnd.nextInt(contro.listaMeseros.size());
        this.mesero = contro.listaMeseros.get(ran);
        lbAtendidoAntes.setText("** Usted estuvo en la mesa "+(rnd.nextInt(10)+1));
        lbAtendido1.setText("Fue atendid@ por "+mesero.getNombre()+", cocinó para");
        int ran2 = rnd.nextInt(contro.listaCajeros.size());
        this.cajero = contro.listaCajeros.get(ran2);
        int ran3 = rnd.nextInt(contro.listaCocineros.size());
        this.cocinero = contro.listaCocineros.get(ran3);
        lbAtendido2.setText("usted "+cocinero.getNombre()+" y pagó en el cajero de "+cajero.getNombre()+" **");
        
        for (Producto p : in.getListaProductosInven()) {
            agregarCb(cbProductos, p.getNombre());
        }
        ListaPedidoMientras.setModel(modeloLista);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                principal.llenadoTablasGeneral();
            }
        });
    }

    public boolean camposVacios(){
        return (tfApellido.getText().isEmpty() && tfDni.getText().isEmpty() && tfEmail.getText().isEmpty() && tfNombre.getText().isEmpty() && tfTelefono.getText().isEmpty());
    }
    
    public void agregarCb(JComboBox<String> combo, String nombre) {
        boolean existe = false;
        for (int i = 0; i < combo.getItemCount(); i++) {
            if (combo.getItemAt(i).equalsIgnoreCase(nombre)) { 
                existe = true;
                break;
            }
        }
        if (!existe) {
            combo.addItem(nombre);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfDni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfTelefono = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        btnRegistrarVenta = new javax.swing.JButton();
        cbProductos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaPedidoMientras = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        btnAgregarPedido = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lbTotal = new javax.swing.JLabel();
        checkRecibo = new javax.swing.JCheckBox();
        lbAtendido1 = new javax.swing.JLabel();
        lbAtendido2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfApellido = new javax.swing.JTextField();
        Apellido = new javax.swing.JLabel();
        lbAtendidoAntes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setText("Nombre");

        tfNombre.setText("we");

        jLabel2.setText("DNI");

        tfDni.setText("12345678");

        jLabel4.setText("E-mail");

        tfTelefono.setText("123456789");

        tfEmail.setText("qw@i.com");

        btnRegistrarVenta.setText("Registrar venta");
        btnRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVentaActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(ListaPedidoMientras);

        jLabel5.setText("Productos a pedir:");

        btnAgregarPedido.setText("Agregar");
        btnAgregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPedidoActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar producto");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lbTotal.setText("Total: ");

        checkRecibo.setText("Generar recibo");

        lbAtendido1.setText("*Fue atendido por {}");

        lbAtendido2.setText("y el cajero {}");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Registrar venta a cliente");

        jLabel3.setText("Telefono");

        tfApellido.setText("wee");

        Apellido.setText("Apellido");

        lbAtendidoAntes.setText("* Estuvo usted en la mesa {}");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnAgregarPedido))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel5)))
                .addGap(0, 31, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfEmail)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbProductos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Apellido)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(lbAtendido1)
                                    .addComponent(lbAtendidoAntes)
                                    .addComponent(lbAtendido2))
                                .addGap(31, 31, 31))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkRecibo)
                            .addComponent(btnRegistrarVenta))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTotal)
                    .addComponent(btnEliminar))
                .addGap(28, 28, 28)
                .addComponent(lbAtendidoAntes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAtendido1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAtendido2)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkRecibo)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVentaActionPerformed
        // TODO add your handling code here:
        String nombre = tfNombre.getText();
        String apellido = tfApellido.getText();
        String dni = tfDni.getText();
        String telefono = tfTelefono.getText();
        String email = tfEmail.getText().trim();
        String patron = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";
        if (camposVacios()){
            JOptionPane.showMessageDialog(this, "Llena los campos.");
            return;
        }
        if (!email.matches(patron)) {
            JOptionPane.showMessageDialog(this, "Correo inválido ❌");
            return;
        }
        if (dni.length() != 8){
            JOptionPane.showMessageDialog(this, "DNI inválido ❌\nDebe ser de 8 dígitos.");
            return;
        }
        if (nombre.isEmpty() || dni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete los datos del cliente.");
            return;
        }
        if (listaMientras.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay productos para registrar.");
            return;
        }
        for (String item : listaMientras) {
            String[] partes = item.split("\\|");
            String nombreProd = partes[0].trim();
            Producto producto = in.getListaProductosInven().stream().filter(p -> p.Nombre.equalsIgnoreCase(nombreProd)).findFirst().orElse(null);
            if (producto == null) {
                JOptionPane.showMessageDialog(this, "El producto " + nombreProd + " no existe en inventario.");
                return;
            }
            if (producto.Stock <= 0) {
                JOptionPane.showMessageDialog(this, "El producto " + nombreProd + " está sin stock.");
                return;
            }
        }
        for (String item : listaMientras) {
            String[] partes = item.split("\\|");
            String nombreProd = partes[0].trim();
            for (Producto p : in.getListaProductosInven()) {
                if (p.Nombre.equalsIgnoreCase(nombreProd)) {
                    p.Stock -= 1;
                if (p.Stock < 0) p.Stock = 0;
                }
            }
        }
        int id = crearID();
        Cliente nuevo = new Cliente(id,total,nombre, apellido, dni, telefono, email);
        nuevo.agregarCompra(listaMientras);
        controlador.agregarAlistaCliente(nuevo);
        Venta nuevaVenta = new Venta();
        nuevaVenta.agregarVentayFecha(id,listaMientras, ahora, nuevo);
        controlador.agregarAlistaVenta(nuevaVenta);
        listaMientras.clear();
        llenadoLista();
        mesero.atendidos = mesero.atendidos + 1;
        cajero.atendidos = cajero.atendidos + 1;
        controlador.setCapital(total);
        if (checkRecibo.isSelected()){
            nuevaVenta.guardarBoleta();
        }
        
        JOptionPane.showMessageDialog(this, "Venta registrada correctamente a " + nuevo.getNombre());
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                principal.notificaciones(1);
            }
        });
        dispose();
    }//GEN-LAST:event_btnRegistrarVentaActionPerformed

    private void btnAgregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPedidoActionPerformed
        // TODO add your handling code here:
        String cliente = (String) cbProductos.getSelectedItem();
        if (camposVacios()){
            JOptionPane.showMessageDialog(this, "Llena los campos.");
            return;
        }
        var a = in.listaProductos.stream().filter(p -> p.Nombre.equalsIgnoreCase(cliente)).findFirst().orElse(null);
        if (a == null) {
            JOptionPane.showMessageDialog(this, "No seleccionaste nada.");
            return;
        }
        long stockActual = listaMientras.stream().filter(p -> p.startsWith(a.getNombre() + " |")).count();
        if (stockActual >= a.getStock()) {
            JOptionPane.showMessageDialog(this, "No hay suficiente stock de " + a.getNombre());
            return;
        }
        listaMientras.add(a.getNombre() + " | " + a.getCategoria() + " | " + a.getPrecio());
        llenadoLista();
    }//GEN-LAST:event_btnAgregarPedidoActionPerformed

    public int crearID(){
        int a_base = random.nextInt(90000);
        int id = a_base + 10000;
        boolean a = controlador.listaVenta.stream().anyMatch(p->p.getID() == id);
        if (a == true){
            crearID();
        }
        return id;
    }
    
    public void llenadoLista() {
        calcularTotalListaTemporal();
        modeloLista.clear();
        for (String p : listaMientras) {
            modeloLista.addElement(p);
        }
        lbTotal.setText("Total :"+total);
    }
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int indice = ListaPedidoMientras.getSelectedIndex();
        if (indice != -1) {
            listaMientras.remove(indice);
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un elemento para eliminar");
        }
        llenadoLista();
    }//GEN-LAST:event_btnEliminarActionPerformed

    public void calcularTotalListaTemporal() {
        total = 0;
        for (String item : listaMientras) {
            String[] partes = item.split("\\|"); // separa por |
            if (partes.length >= 2) {
                try {
                    double precio = Double.parseDouble(partes[2].trim()); // convertimos a double
                    total += precio;
                }catch (NumberFormatException e) {
                    System.out.println("Error al convertir precio: " + partes[2]);
                }
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JList<String> ListaPedidoMientras;
    private javax.swing.JButton btnAgregarPedido;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrarVenta;
    private javax.swing.JComboBox<String> cbProductos;
    private javax.swing.JCheckBox checkRecibo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAtendido1;
    private javax.swing.JLabel lbAtendido2;
    private javax.swing.JLabel lbAtendidoAntes;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfDni;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
